# Generated by Django 5.2.15 on 2026-06-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('crm_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new_client', 'New Client'), ('waiting_payment', 'Waiting Payment'), ('paid', 'Paid'), ('sent', 'Sent'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new_client', max_length=32)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm_messages.chat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'status'], name='orders_orde_shop_id_2cc0ff_idx'), models.Index(fields=['client'], name='orders_orde_client__7a26db_idx'), models.Index(fields=['chat'], name='orders_orde_chat_id_fa3370_idx')],
            },
        ),
    ]
