# Generated by Django 5.2.15 on 2026-06-17 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='clients.client')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='accounts.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm_messages.chat')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['shop', 'client'], name='crm_message_shop_id_cc64f1_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['shop', 'assigned_to'], name='crm_message_shop_id_594f04_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'sent_at'], name='crm_message_chat_id_88387c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction'], name='crm_message_directi_fb941a_idx'),
        ),
    ]
