# Generated by Django 5.2.15 on 2026-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='crm_message_externa_a1f4ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='unique_message_external_id'),
        ),
    ]
