# Generated by Django 5.2.15 on 2026-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_messages', '0002_message_crm_message_externa_a1f4ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='', max_length=16),
        ),
    ]
