# Generated by Django 5.2.15 on 2026-06-18 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teaminvitation'),
        ('clients', '0002_client_instagram_user_id_and_more'),
        ('crm_messages', '0003_message_delivery_error_message_delivery_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='priority',
            field=models.CharField(choices=[('new_clients', 'New Clients'), ('waiting_reply', 'Waiting for Reply'), ('active_orders', 'Active Orders'), ('completed_orders', 'Completed Orders'), ('rejected', 'Rejected Clients')], default='new_clients', max_length=32),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['shop', 'priority'], name='crm_message_shop_id_87e805_idx'),
        ),
    ]
