# Generated by Django 5.2.15 on 2026-06-17 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('support_manager', 'Support Manager')], max_length=32)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='accounts.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'email'], name='accounts_te_shop_id_bc39da_idx'), models.Index(fields=['token'], name='accounts_te_token_8d263f_idx')],
            },
        ),
    ]
