# Generated by Django 5.2.15 on 2026-06-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_username', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'instagram_username'], name='clients_cli_shop_id_8a9b18_idx'), models.Index(fields=['shop', 'display_name'], name='clients_cli_shop_id_49ee29_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'instagram_username'), name='unique_client_instagram_per_shop')],
            },
        ),
    ]
