# Generated by Django 5.2.15 on 2026-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teaminvitation'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instagram_user_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['shop', 'instagram_user_id'], name='clients_cli_shop_id_122f34_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_user_id__gt', '')), fields=('shop', 'instagram_user_id'), name='unique_client_instagram_user_id_per_shop'),
        ),
    ]
