# Generated by Django 5.2.15 on 2026-06-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_teaminvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_user_id', models.CharField(max_length=64)),
                ('instagram_username', models.CharField(max_length=255)),
                ('page_id', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted_access_token', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_connections_created', to=settings.AUTH_USER_MODEL)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_connection', to='accounts.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['instagram_user_id'], name='integration_instagr_5c69e5_idx')],
            },
        ),
    ]
