# Generated by Django 5.2.15 on 2026-06-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teaminvitation'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_webhook_events', to='accounts.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['processed_at'], name='integration_process_8804b3_idx'), models.Index(fields=['shop', 'created_at'], name='integration_shop_id_dfba9c_idx')],
            },
        ),
    ]
